---
title: "Paired report"
author: "Arieanna Eaton"
date: "2024-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
#ROSE gapminder_data <- read_csv("C:/Users/moall/OneDrive/Desktop/un-report/un-report/data/gapminder_data.csv")

#Arieanna gapminder_data <- read_csv("C:/Users/ariea/Desktop/un-report/un-report-rosemln/data/gapminder_data.csv")

```

```{r, echo=FALSE}
ggplot(data = gapminder_data) + 
  aes(x = year, 
      y = pop) + 
  scale_color_brewer(palette = "RdYlBu") +
  labs(x = "Year", 
       y = "Population")  +
  geom_point() + 
  facet_wrap(vars(continent)) +
  theme_minimal()
```

```{r, echo=FALSE}
gapminder_data %>% filter(pop > 1e9) %>% select(country) %>% unique()
```

```{r, echo=FALSE}
gapminder_data %>% 
  filter(country != 'China' & country != 'India') %>%
  ggplot() + 
  aes(x = year, 
      y = pop) + 
  scale_color_brewer(palette = "RdYlBu") +
  labs(x = "Year", 
       y = "Population")  +
  geom_point() + 
  facet_wrap(vars(continent)) +
  theme(axis.text.x=element_text(angle=90))
```

